app = "team-egb-openwa"
primary_region = "iad"

[build]
  image = ""

[[mounts]]
  source = "wwebjs_auth"
  destination = "/app/.wwebjs_auth"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    port = 443

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
